"""BinSense local web server and Gemini vision bridge. Uses Python's standard library only."""

import base64
import json
import os
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


APP_DIR = Path(__file__).resolve().parent
HOST = "127.0.0.1"  # Keep the local API-key bridge private to this computer.
PORT = int(os.environ.get("BINSENSE_PORT", "5050"))
MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.8-flash")
GEMINI_API_KEY = ""
MAX_IMAGE_BYTES = 12 * 1024 * 1024


def load_local_env():
    """Load simple KEY=value entries from a local, gitignored .env file."""
    env_path = APP_DIR / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_local_env()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "").strip()

# The model may choose an item from this sample catalog, but the disposal rules
# and instructions remain in index.html and are never generated by the model.
CATALOG = [
    {"id": "plastic-bottle", "name": "Plastic drink bottle", "visual clues": "clear or coloured plastic beverage bottle"},
    {"id": "aluminium-can", "name": "Aluminium drink can", "visual clues": "metal beverage can"},
    {"id": "glass-jar", "name": "Glass bottle or jar", "visual clues": "glass bottle or food jar"},
    {"id": "cardboard", "name": "Clean cardboard box", "visual clues": "cardboard or paper box; visible heavy food stains mean choose food-stained-paper instead"},
    {"id": "milk-carton", "name": "Drink carton", "visual clues": "beverage carton such as a milk or juice carton"},
    {"id": "banana-peel", "name": "Fruit or vegetable scraps", "visual clues": "recognisable fruit or vegetable scraps, such as a banana peel"},
    {"id": "food-stained-paper", "name": "Food-stained paper packaging", "visual clues": "paper food packaging with clearly visible food or grease contamination"},
    {"id": "tissue", "name": "Tissue paper", "visual clues": "tissue or toilet paper"},
    {"id": "styrofoam", "name": "Styrofoam food container", "visual clues": "expanded polystyrene foam takeaway container"},
    {"id": "battery", "name": "AA / AAA battery", "visual clues": "small cylindrical household battery"},
    {"id": "phone", "name": "Old mobile phone", "visual clues": "mobile phone or smartphone"},
    {"id": "clothing", "name": "Clothing or reusable textile", "visual clues": "recognisable clothes, shoes, or reusable textile such as a shirt, trousers, dress, towel, or bedsheet"},
]
ALLOWED_IDS = {item["id"] for item in CATALOG}


def send_json(handler, status, body):
    encoded = json.dumps(body).encode("utf-8")
    handler.send_response(status)
    handler.send_header("Content-Type", "application/json; charset=utf-8")
    handler.send_header("Content-Length", str(len(encoded)))
    handler.send_header("Cache-Control", "no-store")
    handler.end_headers()
    handler.wfile.write(encoded)


class BinSenseHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(APP_DIR), **kwargs)

    def log_message(self, format_string, *args):
        # Avoid printing request payloads or image information in the terminal.
        print(f"BinSense: {args[0]}")

    def do_GET(self):
        if self.path == "/api/status":
            ready = bool(GEMINI_API_KEY)
            message = (f"Gemini is configured · {MODEL}" if ready else
                       "Add your Gemini API key to the local .env file to enable photo analysis.")
            send_json(self, 200, {"ready": ready, "provider": "Google Gemini",
                                  "model": MODEL, "message": message})
            return
        if self.path.startswith("/api/"):
            send_json(self, 404, {"error": "API route not found."})
            return
        super().do_GET()

    def do_POST(self):
        if self.path != "/api/analyze":
            send_json(self, 404, {"error": "API route not found."})
            return

        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            send_json(self, 400, {"error": "Could not read the image upload."})
            return
        if length <= 0 or length > MAX_IMAGE_BYTES * 2:
            send_json(self, 413, {"error": "This image upload is too large. Try a smaller photo."})
            return

        try:
            payload = json.loads(self.rfile.read(length).decode("utf-8"))
            image_type = payload.get("imageType", "")
            if image_type not in {"image/jpeg", "image/png", "image/webp"}:
                send_json(self, 415, {"error": "Please use a JPG, PNG, or WebP photo."})
                return
            image_data = base64.b64decode(payload.get("image", ""), validate=True)
            if not image_data or len(image_data) > MAX_IMAGE_BYTES:
                send_json(self, 413, {"error": "This image upload is too large. Try a smaller photo."})
                return
        except (json.JSONDecodeError, UnicodeDecodeError, ValueError, TypeError):
            send_json(self, 400, {"error": "That photo could not be read. Please choose it again."})
            return

        if not GEMINI_API_KEY:
            send_json(self, 503, {"error": "Gemini is not configured yet. Add your key to the local .env file, then restart BinSense."})
            return

        prompt = (
            "Inspect this photo for distinct household waste items that can be sorted in a Singapore sorting guide. "
            "Return one entry for each clearly visible item, up to 12; do not count background objects, packaging text, "
            "or parts of the same object as separate items. For each choose exactly one id from this catalog:\n"
            + json.dumps(CATALOG, ensure_ascii=False)
            + "\nUse only visible evidence. Do not infer hidden material, cleanliness, or contents. "
              "Pay attention to visible food or grease on paper packaging. Omit objects that cannot be matched clearly. "
              "Do not give disposal advice. Add a short description if nothing is recognizable."
        )
        item_schema = {
            "type": "OBJECT",
            "properties": {
                "item_id": {"type": "STRING", "enum": sorted(ALLOWED_IDS)},
                "confidence": {"type": "STRING", "enum": ["high", "medium"]},
            },
            "required": ["item_id", "confidence"],
            "propertyOrdering": ["item_id", "confidence"],
        }
        response_schema = {
            "type": "OBJECT",
            "properties": {
                "items": {"type": "ARRAY", "items": item_schema},
                "description": {"type": "STRING"},
            },
            "required": ["items", "description"],
            "propertyOrdering": ["items", "description"],
        }
        request_body = {
            "contents": [{"parts": [
                {"text": prompt},
                {"inline_data": {"mime_type": "image/jpeg", "data": payload["image"]}},
            ]}],
            "generationConfig": {
                "responseMimeType": "application/json",
                "responseSchema": response_schema,
                "temperature": 0,
            },
        }
        request = Request(
            f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent",
            data=json.dumps(request_body).encode("utf-8"),
            headers={"Content-Type": "application/json", "x-goog-api-key": GEMINI_API_KEY},
            method="POST",
        )
        try:
            with urlopen(request, timeout=90) as response:
                answer = json.loads(response.read().decode("utf-8"))
            parts = answer.get("candidates", [{}])[0].get("content", {}).get("parts", [])
            text = next((part.get("text", "") for part in parts if part.get("text")), "")
            recognition = json.loads(text)
            valid_items = []
            for detected in recognition.get("items", [])[:12]:
                item_id = detected.get("item_id")
                confidence = detected.get("confidence")
                if item_id in ALLOWED_IDS and confidence in {"high", "medium"}:
                    valid_items.append({"item_id": item_id, "confidence": confidence})
            send_json(self, 200, {
                "items": valid_items,
                "description": str(recognition.get("description", ""))[:240],
            })
        except HTTPError as error:
            try:
                detail = json.loads(error.read().decode("utf-8", errors="replace"))
                message = detail.get("error", {}).get("message", "")
            except (json.JSONDecodeError, AttributeError):
                message = ""
            if error.code in {401, 403}:
                send_json(self, 502, {"error": "Google rejected the API key. Check the key in your local .env file."})
            elif error.code == 429:
                send_json(self, 429, {"error": "Gemini's free request limit was reached. Wait and try again, or check your AI Studio quota."})
            elif error.code == 404:
                send_json(self, 502, {"error": f"Gemini model {MODEL} was not found. Check GEMINI_MODEL in your local .env file."})
            else:
                send_json(self, 502, {"error": f"Gemini could not analyse this photo ({error.code}). {message[:180]}".strip()})
        except URLError:
            send_json(self, 503, {"error": "Could not connect to Google's Gemini API. Check your internet connection and try again."})
        except (TimeoutError, json.JSONDecodeError, IndexError, KeyError, TypeError):
            send_json(self, 502, {"error": "Gemini returned an unreadable response. Try again with a clearer photo."})


if __name__ == "__main__":
    server = ThreadingHTTPServer((HOST, PORT), BinSenseHandler)
    print(f"BinSense is running at http://{HOST}:{PORT}")
    print(f"Using Gemini model: {MODEL}")
    print("Photos analysed with Gemini are sent to Google's API.")
    print("Keep this Terminal window open while using BinSense. Press Control+C to stop.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping BinSense…")
    finally:
        server.server_close()
